USE CAPPUENSINO;


CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY,
    DATA_CADASTRO DATETIME,
    TIPO_USUARIO VARCHAR(255),
    ENDERECO VARCHAR(255),
    DT_NASC DATE,
    EMAIL VARCHAR(255),
    NOME_USU VARCHAR(255),
    SENHA VARCHAR(255),
    FOTO_PERFIL LONGBLOB,
    TELEFONE VARCHAR(20),
    NUM_IDENTIFICACAO VARCHAR(50),
    ID_STATUS BOOLEAN,
    COR_TELA BOOLEAN
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY,
    DESCRICAO TEXT,
    NOME TEXT
);

CREATE TABLE CURSOS (
    ID_CURSO INT PRIMARY KEY,
    ID_CATEGORIA INT,
    ID_USUARIO INT,
    PRECO DECIMAL(10,2),
    DESCRICAO TEXT,
    TITULO VARCHAR(255),
    DATA_CRIACAO DATETIME,
    DURACAO_TOTAL TIME,
    OBJETIVOS TEXT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MODULO (
    ID_MODULO INT PRIMARY KEY,
    ID_CURSO INT,
    DESCRICAO TEXT,
    TITULO VARCHAR(255),
    ORDEM INT,
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

CREATE TABLE AULA (
    ID_AULA INT PRIMARY KEY,
    ID_MODULO INT,
    NOME VARCHAR(255),
    DURACAO TIME,
    ORDEM INT,
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO)
);

CREATE TABLE MATERIAL (
    ID_MATERIAL INT PRIMARY KEY,
    ID_AULA INT,
    DESCRICAO TEXT,
    URL LONGBLOB,
    DATA_UPLOAD DATETIME,
    TIPO VARCHAR(255),
    TITULO VARCHAR(255),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);

CREATE TABLE ATIVIDADES (
    ID_ATIVIDADE INT PRIMARY KEY,
    ID_MODULO INT,
    TITULO VARCHAR(255),
    DESCRICAO TEXT,
    DATA_CRIACAO DATETIME,
    DURACAO TIME,
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO)
);

CREATE TABLE ATIVIDADES_QUESTOES (
    ID_QUESTAO INT PRIMARY KEY,
    ID_ATIVIDADE INT,
    ENUNCIADO TEXT,
    ALTERNATIVA_CORRETA BOOLEAN,
    URL_ARQUIVO LONGBLOB,
    ALTERNATIVA_1 TEXT,
    ALTERNATIVA_2 TEXT,
    ALTERNATIVA_3 TEXT,
    ALTERNATIVA_4 TEXT,
    ALTERNATIVA_5 TEXT,
    EXTENSAO_ARQUIVO VARCHAR(255),
    FOREIGN KEY (ID_ATIVIDADE) REFERENCES ATIVIDADES(ID_ATIVIDADE)
);

CREATE TABLE QUESTIONARIO (
    ID_QUEST INT PRIMARY KEY,
    TITULO VARCHAR(255),
    DATA_HORA_CRIACAO DATETIME
);

CREATE TABLE QUESTOES (
    COD_QUESTAO INT PRIMARY KEY,
    ID_QUEST INT,
    PERGUNTA VARCHAR(255),
    ORDEM INT,
    ALT_AUDITIVA INT,
    ALT_VISUAL INT,
    ALT_LER_ESCREVER INT,
    ALT_SINESTESICO INT,
    FOREIGN KEY (ID_QUEST) REFERENCES QUESTIONARIO(ID_QUEST)
);

CREATE TABLE ANALISE_APRENDIZAGEM (
    COD_ANALISE INT,
    ID_USUARIO INT,
    RES_AUDITIVA INT,
    RES_VISUAL INT,
    RES_SINESTESICO INT,
    RES_LER_ESCR INT,
    DATA_ANALISE DATETIME,
    PRIMARY KEY(COD_ANALISE, ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE QUEST_ANALISE (
    COD_QUESTAO INT,
    COD_ANALISE INT,
    ID_USUARIO INT,
    RESPOSTA INT,
    PRIMARY KEY(COD_QUESTAO, COD_ANALISE),
    FOREIGN KEY (COD_QUESTAO) REFERENCES QUESTOES(COD_QUESTAO),
    FOREIGN KEY (COD_ANALISE, ID_USUARIO) REFERENCES ANALISE_APRENDIZAGEM(COD_ANALISE, ID_USUARIO)
);

CREATE TABLE PROGRESSO_AULA (
    ID_PROGRESSO INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_AULA INT,
    STATUS BOOLEAN,
    VL_PROGRESSO DECIMAL(10,2),
    DATA_CONCLUSAO DATETIME,
    DATA_INICIO DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);

CREATE TABLE AVALIACAO_CURSO (
    ID_AVALIACAO INT PRIMARY KEY,
    ID_CURSO INT,
    ID_USUARIO INT,
    NOTA INT,
    JUSTIFICATIVA TEXT,
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE SUPORTE (
    ID_MSG INT PRIMARY KEY,
    ID_USUARIO INT,
    NOME VARCHAR(255),
    MENSAGEM TEXT,
    EMAIL VARCHAR(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CONFIG_PROF (
    ID_CONFIG_PROF INT,
    ID_USUARIO INT,
    LINK VARCHAR(255),
    ID_NOTIFICACAO BOOLEAN,
    BIOGRAFIA TEXT,
    CONTA_PAG TEXT,
    AGENCIA_PAG VARCHAR(255),
    CHAVE_PIX VARCHAR(255),
    BANCO_PAG VARCHAR(255),
    PRIMARY KEY(ID_CONFIG_PROF, ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE RESUMOS (
    COD_RESUMO INT,
    ID_USUARIO INT,
    DATA_RESUMO DATETIME,
    TEXTO_RESUMO TEXT,
    PRIMARY KEY(COD_RESUMO, ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PLANOS (
    ID_PLANO INT PRIMARY KEY,
    DESCRICAO TEXT,
    DURACAO TIME,
    PRECO DECIMAL(10,2),
    NOME_PLANO VARCHAR(255)
);

CREATE TABLE COMPRA (
    ID_COMPRA INT PRIMARY KEY,
    ID_USUARIO INT,
    FORMA_PAGAMENTO VARCHAR(255),
    DATA_COMPRA DATETIME,
    STATUS BOOLEAN,
    VALOR DECIMAL(10,2),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CURSOS_COMPRA (
    ID_COMPRA INT,
    ID_CURSO INT,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

CREATE TABLE COMPRA_PLANOS (
    ID_COMPRA INT,
    ID_PLANO INT,
    DATA_FIM DATETIME,
    DATA_INICIO DATETIME,
    PRIMARY KEY(ID_COMPRA, ID_PLANO),
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
    FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO)
);

CREATE TABLE ESTILO_APRENDIZAGEM (
    COD_ESTILO INT PRIMARY KEY,
    NOME_ESTILO VARCHAR(255),
    DESC_ESTILO TEXT,
    TIPO_METODO CHAR(9)
);

CREATE TABLE FUNCIONALIDADE (
    COD_FUNCIONALIDADE INT PRIMARY KEY,
    COD_ESTILO INT,
    NOME_FUNCIONALIDADE VARCHAR(255),
    DESC_FUNCIONALIDADE TEXT,
    FOREIGN KEY (COD_ESTILO) REFERENCES ESTILO_APRENDIZAGEM(COD_ESTILO)
);

SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'CAPPUENSINO' AND REFERENCED_TABLE_NAME IS NOT NULL;